### ISSUE TITLE
[Bug] Incognito - Sandbox(No browser cache) - locale parameter does not work. 

### ISSUE THREAD

**Issue by ktoyoda39** [paypal/paypal-checkout-components#1362] opened 2020-07-14 13:27 UTC
### 🐞 Describe the Bug
For sandbox, when specifying "locale=ja_JP" in an incognito browser(or completely-cache-cleared-browser), "United State" is forced in "Country/Region" in the popup-window from the button.

### 🔬 Minimal Reproduction
Incognito mode browser - Clear all data for the sandbox domain - Sandbox - PayPal Express. like :   
```
<script src="https://www.paypal.com/sdk/js?client-id=sb&currency=JPY&locale=ja_JP&intent=capture&components=buttons,funding-eligibility" data-sdk-integration-source="button-factory"></script>
<script>
  paypal.Buttons({
    style: { shape: 'rect', color: 'gold', layout: 'vertical', label: 'pay', },
    createOrder: function(data, actions) { return actions.order.create({ purchase_units: [{ amount: { value: '1' } }] }); },
    onApprove: function(data, actions) { return actions.order.capture().then(function(details) { alert('Transaction completed by ' + details.payer.name.given_name + '!'); }); }
  }).render('#paypal-button-container');
</script>
```
### 😕 Actual Behavior
![image](https://user-images.githubusercontent.com/40584656/87430284-f67e9c80-c61f-11ea-90c1-969df5952b73.png)

### 🤔 Expected Behavior
the pop-up-window should be Japanese(Country is Japan) like :    
![image](https://user-images.githubusercontent.com/40584656/87430600-6bea6d00-c620-11ea-8206-eed00c4e7369.png)

**Comment by upigilam** [comment] 2020-07-30 19:42
@ktoyoda39 It looks like there was a ramp on sandbox which was causing this issue, locale not being set properly while redirecting and it should be resolved now since the experiment was ramped down to 0% on jul 21st 2020. 

may i request you to verify one more time from your side to check whether the issue is still exists? sorry for the re-verification..

thanks!

**Comment by ktoyoda39** [comment] 2020-07-30 21:43
@upigilam Thank you so much for your update. I confirmed that it works fine on sandbox environment.
Do you know if the same issue exists on production environment ?  
if exists, do you have any idea when it will be fixed ?

**Comment by upigilam** [comment] 2020-07-30 23:22
thanks for verifying, this issue is not present in the production env since the ramp was done in only sandbox environment.
so please close this issue.

thanks!
_Upendra

**Comment by ivankokus** [comment] 2020-07-31 01:33
This issue appears on both sandbox and productions environment for us. Tested a few minutes ago. 

The problem is only for the first time customers, which are pretty much all of them for our business model.

In incognito mode or the first time customer in regular mode, it always shows United States and English instead of Japan and Japanese. 

Once you make one purchase, from the second one it shows Japanese correctly.  Thus, you must clear session before testing or use incognito mode to see the bug.

Please fo not close this issue as it’s not fixed.

**Comment by ivankokus** [comment] 2020-07-31 01:36
BTW, I noticed the same behavior for Russian and Brazilian Portuguese, while other languages where fine.  Basically it happens for all languages where it opens PayPal window in a popup instead of inline.

**Comment by mstuart** [comment] 2020-08-04 22:40
@upigilam, can you check on this? ^^ @ivankokus mentioned it also happens in production?

**Comment by ivankokus** [comment] 2020-08-11 04:40
This appears to suddenly be fixed in both sandbox and production without us making any changes to our code.  Has a fix been deployed?

**Comment by mstuart** [comment] 2020-09-01 14:48
@upigilam, can you verify that a fix has been deployed?

**Closed by mstuart** 2020-09-01 14:48 UTC
Labels: 🌹 has-reproduction, 🐞 bug
