### ISSUE TITLE
[Documentation] If popup closes immediately

### ISSUE THREAD

**Issue by jniclas** [paypal/paypal-checkout-components#1662] opened 2021-06-07 17:41 UTC
### 📙 Describe the Issue
I have the problem that when I try to press the paypal button a second time after closing the popup window from the first time, the paypal popup window closes immediately. 

### 😕 Actual Behavior
After logging into the popup window with a sandbox account and closing it, I get the error:
```
Create Subscription Api response error:

{
    "name": "NOT_AUTHORIZED",
    "message": "Authorization failed due to insufficient permissions.",
    "debug_id": "...",
    "details": [
        {
            "issue": "PERMISSION_DENIED",
            "description": "You do not have permission to access or perform operations on this resource."
        }
    ],
    "links": [
        {
            "href": "https://developer.paypal.com/docs/api/v1/billing/subscriptions#NOT_AUTHORIZED",
            "rel": "information_link",
            "method": "GET"
        }
    ]
}
```
The error appears only if the endpoint ```https://www.sandbox.paypal.com/graphql?UpgradeFacilitatorAccessToken``` was called. Which happens on the login in the window. 

### 🤔 Expected Behavior
The window should stay in front of the application.

### My Solution
The endpoint ```UpgradeFacilitatorAccessToken``` seems to be updating a token, so maybe the props are outdated of the button. So I added the method refreshProps to the onCancel Event:
```
onCancel: function (data, actions) {
  button.updateProps();
},
``` 
Now the popup window stays in front of my application no matter how many times I close it.
Maybe you could extend a troubleshooting section in the documentation?

With best regards
Niclas

**Comment by johan123312321** [comment] 2021-06-07 22:38
Hi @jniclas! I'm experiencing the same issue with react-paypal-js library. 
https://github.com/paypal/react-paypal-js/issues/117 

The issue started to appear for me without any library update (before it worked as expected). Probably it is related to some breaking change in the PayPal backend.

**Comment by ravishekhar** [comment] 2021-06-08 13:20
@jniclas @johan123312321 Can you pls provide a sample button to reproduce the issue.

**Comment by jniclas** [comment] 2021-06-08 20:59
Hey,
I just created a small project to reproduce the Issue. Its hostet at https://paypal.niiclas.de/ .

**Comment by johan123312321** [comment] 2021-06-09 21:48
Hi @jniclas @ravishekhar ! I just noticed that problem occurs only with subscriptions. With orders works correctly.

**Comment by mnicpt** [comment] 2021-06-10 11:34
A fix is going for this hopefully today. The issue is that when the token is upgraded, it is missing the subscriptions scope. We will be preventing this upgrade for subscriptions.

**Comment by johan123312321** [comment] 2021-06-10 12:47
@mnicpt please update dependency also in https://github.com/paypal/react-paypal-js library, after fix will be implemented.

**Comment by gregjopa** [comment] 2021-06-15 14:56
This fix went out last Thursday (6/10/2021) and resolved this issue. I'm going to close this one out. 

@johan123312321 react-paypal-js load the JS SDK evergreen script so it automatically picks up this fix. Let us know if you are still experiencing issues.

**Closed by gregjopa** 2021-06-15 14:56 UTC
