### ISSUE TITLE
unhandled_error [Error: Window closed] in iOS WebView Safari

### ISSUE THREAD

**Issue by bizready** [paypal/paypal-checkout-components#1302] opened 2020-05-07 16:23 UTC
### PayPal Smart Button: unhandled error when load/click on the buttons

<img width="914" alt="Screen Shot 2020-05-07 at 12 10 56 PM" src="https://user-images.githubusercontent.com/63766875/81318323-1613aa80-905c-11ea-9b8b-cdf84a115668.png">

- code snippet
```
export default {
  data() {
    return {
      isLoaded: false,
      isFund: false,
      creditBalance: 0,
      product: {
        amount: '50',
        description: 'test product',
        img: ''
      }
    };
  },
  mounted() {
    console.log('mounted start');
    const script = document.createElement('script');
    script.src =
      'https://www.paypal.com/sdk/js?client-id=Ab7NisBf7fowrKaozO2lgGhI8f2-u8LIOEQh3sq-kVUfVdzYEYmxYhfWROBk2Xh9i51RGSWseF7ShX08';
    script.addEventListener('load', this.setLoaded);
    document.body.appendChild(script);
    console.log('mounted end');
  },
  methods: {
    setPaid() {
      this.isFund = true;
    },
    setLoaded() {
      this.isLoaded = true;
      window.paypal
        .Buttons({
          style: {
            layout: 'vertical',
            color: 'blue',
            shape: 'rect',
            label: 'paypal',
            size: 'responsive'
          },
          createOrder: (data, actions) => {
            return actions.order.create({
              //given_name, email_address
              purchase_units: [
                {
                  amount: {
                    value: this.product.amount
                  }
                }
              ]
            });
          },
          onApprove: (data, actions) => {
            this.setPaid();
            return actions.order.capture().then(function(details) {
              console.log(
                'Transaction completed by ' + details.payer.name.given_name
              );
            });
          },
          onError: err => {
            console.log('error:', err);
          }
        })
        .render(this.$refs.paypal);
    }
  }
};
```
- Do not see `paypal.version`in my browser console
- The exact browser version
<img width="278" alt="Screen Shot 2020-05-07 at 12 21 08 PM" src="https://user-images.githubusercontent.com/63766875/81319166-4740aa80-905d-11ea-8ae1-7d80f0621f65.png">

### Steps to reproduce
Load payment module that as PayPal buttons
Click on one of the buttons

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

**Comment by csheppard** [comment] 2020-05-07 19:58
#1290

**Comment by bluepnume** [comment] 2020-05-08 00:26
Thanks - yeah this is a duplicate of https://github.com/paypal/paypal-checkout-components/issues/1290 -- trying to find some capacity to look into this one. Thanks!

**Closed** 2020-05-08 00:33 UTC
