### ISSUE TITLE
[Bug] We are having trouble contacting our credit cards processing provider. Please use PayPal or try again later.

### ISSUE THREAD

**Issue by Kocaak** [paypal/paypal-checkout-components#2244] opened 2023-09-13 14:47 UTC
### 🐞 Describe the Bug

Copilot payment via credit/debit card is buggy.

### 🔬 Minimal Reproduction

Easily can be reproduced by going to signup page of copilot: https://github.com/github-copilot/signup/billing?payment_duration=yearly

### Affected browsers

What browser(s) are affected?

Chrome

### ➕ Additional Context

![Screenshot 2023-09-13 165031](https://github.com/paypal/paypal-checkout-components/assets/36338313/f9b40834-4dda-4291-bac7-487793e4d719)

**Comment by devchristina** [comment] 2023-09-13 16:36
Hi @Kocaak -- checking with out professional services team to see if this is a known issue. Apologies for any issues this is creating with you signing up for co-pilot.

**Comment by devchristina** [comment] 2023-09-13 16:37
Also, did you use PayPal and see the same error?

**Comment by Kocaak** [comment] 2023-09-13 16:40
Hi, @devchristina thanks for your comment. I prefer to not use Paypal at all so don't have a paypal account.

**Comment by Kocaak** [comment] 2023-09-13 16:40
Hi, @devchristina thanks for your comment. I prefer to not use Paypal at all so don't have a paypal account.

**Comment by devchristina** [comment] 2023-09-13 16:43
Got it. I'm not confident that GitHub is utilizing PayPal for their credit/debit card processing. We'll need to confirm that first. If they are not, this issue will need to be submitted to the GitHub team. If PayPal is processing their credit/debit cards, I'll continue to work on trying to understand the root cause. I'll reply once I have this answer.

**Comment by devchristina** [comment] 2023-09-13 22:26
Hi @Kocaak -- I've confirmed that the function of paying with a debit/credit card is not handled by PayPal. You'll need to submit a ticket with [GitHub](https://support.github.com/) about the inability to sign up successfully for GitHub Co-Pilot. 

I'll close this ticket as there's nothing we can do here at PayPal.

**Closed by devchristina** 2023-09-13 22:26 UTC
