### ISSUE TITLE
Incorrect Paypal Login followed by Cancel does not result in cancel callback being invoked

### ISSUE THREAD

**Issue by satyamallya** [paypal/paypal-checkout-components#793] opened 2018-08-14 16:15 UTC
We use Paypal Checkout.js for getting  billing agreement from the user.

In our scenario, we are noticing the following 

User taps on the PayPal Checkout button,  logs in with either incorrect login or password atleast once and then taps on the cancel link at the bottom. This does not result in the cancel event handler being invoked.  

Here is our skeleton code

paypal.Button.render(
            {
                env: deducePayPalEnv(),
                style: {
                    tagline: false
                },
                payment: function () {
                    return paypalCheckoutInstance.createPayment(paymentOpts);
                },

                onAuthorize: function (data, actions) {
                    // logEvent: payment successful
                    console.log("Successfully authorized");
                },

                onCancel: function (data) {
                    // logEvent: pre-pdp paypal-login-cancelled
                     console.log("Cancelled by user");
                },

                onError: function (err) {
                    // logEvent: pre-pdp paypal-login-error
                     console.log("Error ");
                }
            },
            divIdForPayPalBtn);
    };

The same code works as  expected interaction
a) User taps on the PayPal Checkout button, Logs and authorizes Billing Agreement. As expected this results in OnAuthorize event being invoked 
b) User taps on the PayPal Checkout button, does not login, just presses cancel, this results in OnCancel event handler being invoked

It appears incorrectly logging in before Cancel causes this issue. The problem occurs on iOS, Android and on desktop.
Please provide a short description of the issue here, along with:

This issue is repeatable

### Steps to reproduce

1. tap on the PayPal Checkout button
 
2.  Enter incorrect PayPal login (correct email and incorrect password)
 
3.  Click on “Cancel and return “ link on PayPal login screen
 
4.  The cancel callback is not triggered

**Comment by mcntsh** [comment] 2018-11-06 01:32
Hey @satyamallya I can also repro this issue. I've taken it to an internal team and will update this ticket when a fix is out.

**Comment by mcntsh** [comment] 2019-01-09 18:33
@angel-carvajal I just followed up with that team and a fix will be going out next week. I'll keep track of it and update this issue after the release.

**Comment by bluepnume** [comment] 2019-02-08 09:22
Are we good on this one?

**Comment by mcntsh** [comment] 2019-02-19 17:48
The fix went out last week -- I just got confirmation from the team. 

Closing this one out! Please feel free to open it back up if the issue comes back.

**Comment by superp** [comment] 2019-02-20 12:01
Hi there!

@mcntsh  I have the last version v4 - 4.0.257, and I still to reproduce this bug.
In my case:
1) Click to Paypal Button
2) Don't login to paypal account
3) Click to Cancel and return to merchant
4) onCancel callback don't invoke 

It's a very important issue for me because the user can click to my paypal button again and a will have duplicate orders...

**Comment by superp** [comment] 2019-02-22 10:56
Any news on this?

**Comment by superp** [comment] 2019-02-25 08:17
I see that you've realized new version 4.0.258, but I still reproduce this bug :(

**Comment by bluepnume** [comment] 2019-02-25 22:28
@mcntsh can you check if this fix was actually rolled out?

**Comment by superp** [comment] 2019-03-05 06:14
@bluepnume @mcntsh 
I've started implementing the new checkout SDK and saw the same problem with the Cancel button (at paypal.com site example):
https://monosnap.com/file/qu5q7SZTpjSn87FNhuMvnSfsYiTs6r

**Comment by bluepnume** [comment] 2019-05-03 02:54
This should be resolved now. Please let me know if you still see the issue.

**Closed by bluepnume** 2019-05-03 02:54 UTC
Labels: bug, p2

**Comment by superp** [comment] 2019-05-03 08:26
It works on latest version 4.0.267
Thanks!
