### ISSUE TITLE
[Bug] findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by Maxeeezy** [paypal/paypal-checkout-components#1579] opened 2021-03-19 09:54 UTC
The bug appears when implementing the PayPalButton to create a subscription. The message above is written in the console.

To reproduce, implement PayPalButton in React project.

Expected behaviour should be that the error message dissapears.

Concerning this issue, there was a thread opened before: https://github.com/paypal/paypal-checkout-components/issues/1448

However, adding the new paypal sdk did not fix the problem.

What can i do to fix this bug on react? Thank you in advance.

**Comment by gregjopa** [comment] 2021-04-06 13:58
Hi @Maxeeezy, thanks for reporting the issue. I went ahead and re-opened #1448. It was accidentally closed.

The problem is with the react driver in zoid that the PayPal JS SDK uses. It lives here: https://github.com/krakenjs/zoid/blob/master/src/drivers/react.js#L46. Ideally the `findDOMNode()` call should be replaced with a ref to avoid the warning all together. 

Let's use #1448 to track this problem. I'm going to close this one out as a duplicate.

**Closed by gregjopa** 2021-04-06 13:58 UTC
