### ISSUE TITLE
[Bug] "Unable to delegate rendering... Error: No ack for postMessage " issue

### ISSUE THREAD

**Issue by MikeTodd** [paypal/paypal-checkout-components#1332] opened 2020-06-10 20:13 UTC
### 🐞 Describe the Bug

Some of our users (a fairly small percent, but we have several reports of this) are getting the following error when our site tries to show them the Smart Payment Buttons:

Paypal returned the following error: Error: Unable to delegate rendering. Possibly the component is not loaded in the target window. Error: No ack for postMessage zoid_delegate_paypal_checkout in https://www.paypal.com in 10000ms at https://www.paypal.com/sdk/js?client-id=(id-here)

The affected users consistently get this error, and it's across various browsers that are up-to-date (the same users have even tried multiple browsers). But for most of our users, things work as expected and they don't get this error. We have not been able to identify any differentiators between users that get this error, and those that don't.

### 🔬 Minimal Reproduction

We cannot reproduce this error ourselves, but several of our users are experiencing it (but only a small fraction). If you want to try to reproduce, you can go to http://www.drivethrurpg.com, add a (non-free) item to your cart, log in, and then go through checkout until you get to the payment page (https://www.drivethrurpg.com/checkout_payment.php). Add the GET variable show_paypal_sb=1 (so the URL would be https://www.drivethrurpg.com/checkout_payment.php?show_paypal_sb=1) and load the page that way. This will force the Smart Payment Buttons module to be enabled for you. Select "Other payment method" and then click Review Order.

If the error appears for you, it will be on that Review Order page.

### 😕 Actual Behavior

When attempting to show Smart Payment Buttons, user gets the error:

Error: Unable to delegate rendering. Possibly the component is not loaded in the target window. Error: No ack for postMessage zoid_delegate_paypal_checkout in https://www.paypal.com in 10000ms at https://www.paypal.com/sdk/js?client-id=(id-here)

### 🤔 Expected Behavior

User should be shown Smart Payment Buttons

### 🌍 Environment

- Browser version: Chrome 83.0.4103.97, Firefox 77.0.1
- OS version: Windows 10 (probably others as well)
- SDK version: latest/current; we load directly from https://www.paypal.com/sdk/js?client-id=sb

### Affected browsers

Most likely all browsers, but we have confirmation that it is at least happening in the latest versions of Chrome and Firefox.

### ➕ Additional Context

We have already looked at  https://github.com/paypal/paypal-checkout-components/issues/429 and https://github.com/paypal/paypal-checkout-components/issues/140 -- neither applies here. We are not using an iframe, and even if we were, we are already including the .js file in the top-level window. And we aren’t using the older version of checkout.js, we are using the smart buttons script from https://www.paypal.com/sdk/js

**Comment by MikeTodd** [comment] 2020-06-11 16:34
As a note, we’ve disabled the Smart Buttons module until we can resolve this issue, so currently the payment page is just using our older PayPal integration. We are working on adding a GET variable that will force it on, for testing purposes.

**Comment by bluepnume** [comment] 2020-06-17 00:44
Hi Steve, mind taking a look into this one? Thanks!

**Comment by mnicpt** [comment] 2020-06-17 00:45
Not at all.

**Comment by MikeTodd** [comment] 2020-06-17 17:07
Because we were having several users with this issue, and it prevented them from being able to check out, we disabled this payment module and went back Website Payments Pro. So to answer your question: no, we were not able to find out if there were any console errors with those users, unfortunately.

**Comment by mnicpt** [comment] 2020-06-17 18:41
@MikeTodd  Because the PayPal Smart Buttons require IE 11+ (https://developer.paypal.com/docs/checkout/troubleshoot/support/), I would recommend enabling the PayPal Smart Button for IE 11 and above and fallback to Payments Pro for IE 10 and below.  Anything else I can help you with before I close this issue?

**Comment by MikeTodd** [comment] 2020-06-17 18:56
@mnicpt this issue is occurring in the latest version of Chrome and Firefox. It's an issue that these users have replicated, so it happens every time. We are trying to get in contact with them to see if we can have them try again, but so far none have responded to say they'll help us debug. Since this is not an IE issue, and it is an issue that particular users encounter reliably (even though we can't reproduce it ourselves), I think it's worthy as keeping open.

What circumstances cause the error "No ack for postMessage zoid_delegate_paypal_checkout" to be thrown? That sounds rather cryptic, so I was hoping someone with more knowledge of the library could look at that and give us more information.

**Comment by mnicpt** [comment] 2020-06-17 19:50
@MikeTodd I'm sorry.  I saw Windows 10 and thought IE 10.  The circumstance that would cause the error `No ack for postMessage zoid_delegate_paypal_checkout` is that the iframe is trying to communicate back to the Buttons component from the script and does not get a response.  I would try decoupling, loading the script through `$.loadScript` with the $.showPaypalButtons() as the callback and instead load the script asynchronously on the payment page, and then call `$.showPaypalButtons` on the confirmation page.  This may allow time for the button component to be ready when it is sent a message from the iframe.  I would also call `$("a#btn-next").closest("div").hide();` after `paypal.Buttons()` to eliminate the possibility it throw any errors and doesn't execute `paypal.Buttons()`.  I haven't been able to cause it to error, but wouldn't hurt.  Hope this helps.

**Comment by MikeTodd** [comment] 2020-06-17 20:34
Ok thanks @mnicpt, I'm relaying that to our developer and will see what he says. He's in the middle of another project right now, but hopefully that change will be easy and we can get one of the customers who reported the error to try it again.

**Comment by mnicpt** [comment] 2020-06-17 20:36
👍 Is it ok if I close this issue, or would you like to keep it open?

**Comment by MikeTodd** [comment] 2020-06-17 21:26
Yeah go ahead and close it for now, as long as we can re-open it if we get more information and the solution above doesn't fix the issue.

**Comment by mnicpt** [comment] 2020-06-18 13:45
@MikeTodd If you are unable to resolve after the above changes, please call me out specifically in a new issue.  Thanks.

**Closed by mnicpt** 2020-06-18 13:45 UTC
Labels: bug

**Comment by hbstone** [comment] 2020-08-02 06:14
@MikeTodd I'm trying to buy something right now on drivethrurpg.com and am consistently getting this error... I googled to find out if it was a thing and found this issue.

I'm a web dev so hopefully able to provide whatever info you need to help debug.

**Comment by bluepnume** [comment] 2020-08-02 06:19
@hbstone I see drivethurpg.com has `pointer-events: none;` on the paypal button container. That will stop it from working.

<img width="1131" alt="Screen Shot 2020-08-01 at 11 18 46 PM" src="https://user-images.githubusercontent.com/1219075/89116838-62993700-d44d-11ea-867d-86cf57c119f8.png">

**Comment by MikeTodd** [comment] 2020-08-03 13:59
@bluepnume you're looking at the payment selection page. The actual payment buttons are shown on the confirmation page (the next step).

@hbstone I'll have the developer that's working on this bug get in touch with you. It would be very helpful to have info from an actual web developer who can reproduce this. Thank you!

**Comment by MikeTodd** [comment] 2020-08-03 14:02
@hbstone could you email me (my username here at onebookshelf.com) so that I can get you in touch with that dev? We'll be more than happy to give you store credit for helping us.

**Comment by MikeTodd** [comment] 2020-08-31 19:27
Just to leave a note/update: after further investigation, it seems like this happened for larger carts/orders, where it took our system a while to actually create said order, and the PayPal library treated it as a timeout.

**Comment by hbstone** [comment] 2020-09-07 06:11
Makes sense; when I was able to repro this it was with only one "item" in the cart but that item was a pretty big bundle. That's probably why I couldn't repro it later with an actual single item in the cart.

Glad to hear you figured it out!

**Comment by Etto91** [comment] 2021-02-17 15:23
i got this error
`No ack for postMessage gn() in https://www.paypal.com in 10000ms`
but from your comments, i can't understand what i have to do to fix the problem
can someone help me?

**Comment by JorgeCauich** [comment] 2021-04-17 22:24
I got tgus error
Error: No ack for postMessage zoid_delegate_paypal_checkout in https://www.sandbox.paypal.com in 10000ms
@MikeTodd 
can someone help me?

**Comment by mnicpt** [comment] 2021-04-19 13:46
@JorgeCauich Please open a new issue with your concern and please include more information to help us debug.  (i.e. screenshots, steps to reproduce, console errors, etc.  Thank you!

**Comment by cyanyiyi** [comment] 2022-02-11 13:30
When I import  “sensors analytics” in my project, ie11 show this error 

unhandled_error [object Object]
SCRIPT5022: No ack for postMessage onInit() in https://www.sandbox.paypal.com in 10000ms
buttons (1318,88771)

I use @paypal/paypal-js and paypal SDK load success, but render failed。

**Comment by Mike-E-angelo** [comment] 2022-07-31 07:04
Still an issue
