### ISSUE TITLE
when clicking the "try again" button i get "Expected element to be passed to render iframe"

### ISSUE THREAD

**Issue by zvihersh** [paypal/paypal-checkout-components#1325] opened 2020-06-02 16:48 UTC
### Description

Please provide a short description of the issue here, along with:
after entering a wrong card number i get the "something went wrong" message along with "try again" button, when i press the "try again" button nothing happens in the screen but i get this error on the console:
Error: Expected element to be passed to render iframe

- Screenshots or videos that show the issue
![1](https://user-images.githubusercontent.com/25309866/83546210-00818b80-a509-11ea-948f-243826eedcb3.png)

- All console logs during the time of the issue, especially error messages

"Error: Expected element to be passed to render iframe
    at https://www.paypal.com/sdk/js?client-id=myId:2:101549
    at https://www.paypal.com/sdk/js?client-id=my:2:101609
    at e.n.dispatch (https://www.paypal.com/sdk/js?client-id=myId:2:9724)
    at e.n.then (https://www.paypal.com/sdk/js?client-id=myId:2:10472)
    at r (https://www.paypal.com/sdk/js?client-id=myId:2:101356)
    at Object.renderTo (https://www.paypal.com/sdk/js?client-id=myId:2:101814)
    at https://www.paypalobjects.com/inlineGuest/app.322d06ae39ab3e3a90a2ea984c42d90b.js:1:582142
    at Object.u (https://www.paypalobjects.com/inlineGuest/vendor.322d06ae39ab3e3a90a2ea984c42d90b.js:1:187120)
    at l (https://www.paypalobjects.com/inlineGuest/vendor.322d06ae39ab3e3a90a2ea984c42d90b.js:1:187203)
    at i (https://www.paypalobjects.com/inlineGuest/vendor.322d06ae39ab3e3a90a2ea984c42d90b.js:1:187258)"
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
yes

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment] 2020-06-02 17:49
@khanghoang can you take a look?

I'm guessing when we call `paypal.Checkout().render('body')` from the card iframe, we're missing the `'body'`.

**Comment by mstuart** [comment] 2020-08-04 23:05
Hi @zvihersh, are you still able to reproduce this issue? Tested it and it seems to be working.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/742884/89353874-fe5cba00-d67c-11ea-9be8-903b7136a30b.png">

Closing the issue for now. If it's still occurring, please re-open the issue. Thanks!

**Closed by mstuart** 2020-08-04 23:05 UTC
Labels: standard-cards, 🌹 has-reproduction, 🐞 bug
