### ISSUE TITLE
[Bug] onApprove randomly not called when using PayPal subscriptions

### ISSUE THREAD

**Issue by TunMovil** [paypal/paypal-checkout-components#2112] opened 2023-02-27 19:01 UTC
### 🐞 Describe the Bug
I just create a new bug report using the info on https://github.com/paypal/paypal-checkout-components/issues/1971 because is exactly the same issue we have...

This bug is very similar to https://github.com/paypal/paypal-checkout-components/issues/1971: since a few weeks/months, we have new subscriptions checkout flow that never return, and onApprove and never called.

This generates a lot a frustrations and extra operations: some customers retry to create new subscriptions generating multiple payments. Sometimes we are never able to do the link between a Paypal subscription a customer accounts, which leads to having us cancelling subscriptions and refunding.

Unfortunately based on the available current flow design (https://developer.paypal.com/docs/subscriptions/integrate/), there are no other reliable way to obtain the Subscription ID before launching the check out.

### 🔬 Minimal Reproduction
We have not been able to reproduce this in sandbox yet.

### 😕 Actual Behavior
`onApprove` is never called, and we are then never able to link Paypal subscriptions to our customer accounts.

### 🤔 Expected Behavior
`onApprove` to be called in a reliable way.

### 🌍 Environment

- Browser version: - Any
- OS version: - Any
- SDK version (`window.paypal.version`): - 5.0.356

### Affected browsers
What browser(s) are affected?

N/A

### ➕ Additional Context
...

**Comment by barshag** [comment] 2023-03-07 17:27
Also here with just one-time payment...:(

**Comment by DanieleMancini** [comment] 2023-03-28 16:09
same here, payment received but onApprove not called, that already appened in the past: #1813

**Comment by stefanosalvucci** [comment] 2023-03-28 16:26
Hello @wsbrunson @wickerpopstar, this is happening also to us.
This was opened 1 month ago and we still do not have any update on your side.

Could you please provide some information?

**Comment by stefanosalvucci** [comment] 2023-03-30 17:39
Hello, @barshag @TunMovil, do you still have this issue?

**Comment by TunMovil** [comment] 2023-04-17 17:10
Hello @stefanosalvucci, yes, this keeps happening to us randomly...

**Comment by DanieleMancini** [comment] 2023-04-27 08:13
still happening, not only for subscriptions, can we please have an answer from paypal team?

window.paypal.version '5.0.368'

**Comment by salievos** [comment] 2023-06-13 12:06
Hi there. I think my problem is also related to this bug, when onApprove called, there is an exception when trying `actions.subscription.get()`. When I'm trying to log the  exception using `JSON.stringify()` - I'm getting empty object, but charges and subscriptions were created in paypal. Also can't reproduce this issue, somehow it happens randomly.

**Comment by devchristina** [comment] 2023-09-13 19:07
Hi All -- apologies in the delay of acknowledgement of this issue and/or response. I'll work with the team to look into what's going on. Can anyone here advise if this is still an issue?

**Comment by devchristina** [comment] 2023-09-21 23:43
Hi All -- Coming back with an update. We're still triaging this issue to find a solution. One suggestion would be to ensure the solution has registered a Webhook to listen for PAYMENT.SALE.COMPLETED events. 

Documentation on that is here: https://developer.paypal.com/api/rest/webhooks/ & https://developer.paypal.com/api/rest/webhooks/event-names/#link-sales

**Comment by stefanosalvucci** [comment] 2023-09-28 12:46
Hello @devchristina we just find out that our checkout in production have a similar problem. In details:

- on a paypal checkout for a subscription when the user completes the purchase, the onApprove function is _never_ called so we cannot redirect the customer to the thankyou page. This was not happening before. We discovered it today while doing a demo with a potential customer.

Did you have released something in the past days?
Thank you

**Comment by Tronhus** [comment] 2023-09-28 13:05
Hello @devchristina we experience the same as @stefanosalvucci our site don't call onApprove when purcase is done. 
testet in Chrome, Safari and Firefox. 
we have debugged the error and found the following error

throw new Error("SDK Validation error: 'Expected client-id to be passed'" );
/* Original Error:
Expected client-id to be passed (debug id: f11258836e07b)
*/
Thank You
Regards 
Thomas

**Comment by 8ctopus** [comment] 2023-09-28 13:13
https://github.com/paypal-examples/paypal-dev-support/issues/11

**Comment by devchristina** [comment] 2023-09-28 14:04
Acknowledging the latest comments on this issue -- Working with our Engineers to understand what's happening.

**Comment by seedj** [comment] 2023-09-28 16:50
Following this issue

**Comment by Tronhus** [comment] 2023-09-29 05:19
We have testet our paypal payment, and can confirm that the problem is fixed 
Regards 
Thomas

**Comment by 8ctopus** [comment] 2023-09-29 06:07
Yes fixed in sandbox as well on my side

**Comment by ipsod** [comment] 2023-10-16 15:49
I'm having this same issue, but with onShippingChange.  I have automated tests that expect this to happen, and they might fail 5x in a row or succeed 5x in a row, without any changes to the tests or the code.

**Comment by sebastianfdz** [comment] 2023-12-07 16:58
> I'm having this same issue, but with onShippingChange. I have automated tests that expect onShippingChange to happen when the user logs in (so that I can update shipping rates with user's location), and the tests might fail many times in a row or might succeed many in a row, with no changes to the tests or other code.

Hi @ipsod! Thanks for reaching out. It seems like that is a separate issue from the original problem on this one (onApprove). We want to make sure we are keeping track of the different issues that are raised. If this is still happening for you, could I ask you to create a separate issue so that we can take a closer look? 

Thanks!

**Comment by sebastianfdz** [comment] 2023-12-07 16:58
Hello all! It seems like the onApprove issue has been resolved based on the last comments. I'm going to go ahead and mark this issue as closed. Thanks @devchristina for managing this!

**Closed by sebastianfdz** 2023-12-07 16:58 UTC
Labels: 🏓 awaiting-response, ⁉️ question
