### ISSUE TITLE
Rendering credit or debit card on my website

### ISSUE THREAD

**Issue by Mansi1** [paypal/paypal-checkout-components#1417] opened 2020-08-28 17:17 UTC
### 🐞 Describe the Bug
Rendering debit and credit card in my website
![image](https://user-images.githubusercontent.com/12079044/91594907-f1bd4000-e962-11ea-80a5-b3a324cd61a2.png)

it will destroy the design, 
 - user can not choose an different payment method. 
 - no back button or cancel

**Comment by mstuart** [comment] 2020-08-28 17:25
Hi @Mansi1, thanks for opening this issue. Agreed that the lack of a back button is frustrating. This is a duplicate of #1358. I'll mention this issue there, so we don't lose the reference to the screenshot you posted above. Closing this issue for now and we'll keep #1358 open.

/cc @khanghoang for FYI

**Closed by mstuart** 2020-08-28 17:25 UTC
Labels: 🐞 bug
