### ISSUE TITLE
PayPal SDK Buttons: unhandled_error [Error: Window closed]

### ISSUE THREAD

**Issue by cusero** [paypal/paypal-checkout-components#1290] opened 2020-04-02 16:31 UTC
### PayPal Smart Button: unhandled error when popup closed before it loads

<img width="1325" alt="Screen Shot 2020-04-02 at 17 20 46" src="https://user-images.githubusercontent.com/14952750/78273407-b418d000-7506-11ea-98c7-210409677320.png">

* `paypal.version`: 5.0.117
* Chrome: Version: 80.0.3987.162 
* Cannot provide a public URL (yet)
* Error _always_ occurs
* Also occurs in https://developer.paypal.com/demo/checkout

Code snippet:
```
paypal.Buttons({
        style: {
            layout: 'vertical',
            color: 'gold',
            shape: 'pill',
            label: 'paypal'
        },
        env: 'sandbox',
        client: {
            sandbox,
            production
        },
        locale: 'en_GB',
        createBillingAgreement: onPaypalCreateBillingAgreement,
        onApprove: onPaypalApprovedPayment,
        onCancel: onPaymentCancelled,
        onError: onPaymentError
    }).render('#braintree-paypal-cta');
```

Where `onPaypalCreateBillingAgreement` simply does `paypalCheckoutInstance.createPayment({ flow: 'vault', enableShippingAddress: false })`

### Steps to reproduce

1. Click on PayPal Smart Button
2. Close the popup before loader stops

### Affected browsers

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by saxinte** [comment] 2020-04-02 16:54
+1

**Comment by bluepnume** [comment] 2020-04-02 17:07
Hi -- do you see any errors or failing urls in network tab as you click?

**Comment by thefotios** [comment] 2020-04-03 01:19
Um, so it looks like PayPal decided to release a patch update 2 days ago that changed the default from `authorize` to `capture`?!?! https://github.com/paypal/paypal-checkout-components/compare/v4.0.311...v4.0.312

We started seeing a slow decline in PayPal payments that directly correlated to this release. My guess is for anybody lucky enough to not have a failure, they had the script cached.

**Comment by bluepnume** [comment] 2020-04-03 01:20
Hi @thefotios -- can you let me know exactly what you're seeing?

**Comment by thefotios** [comment] 2020-04-03 01:24
@bluepnume I'm passing `intent=authorize` to the SDK, but I'm getting this error in the console: 
```
Uncaught Error: Expected intent from order api call to be authorize, got capture. Please ensure you are passing intent=capture to the sdk
```

I should mention that we're using `braintree-web`, but we're explicitly passing `authorize` there as well.

It's very suspect that this commit landed in the `4.x` release right when this started happening - https://github.com/paypal/paypal-checkout-components/commit/bc3dbb7fa9959c65bf930c9baf9f03aed2e110ec

**Comment by bluepnume** [comment] 2020-04-03 01:27
@thefotios -- can you share:

a) An example of the code you're using with braintree-web to set up the transaction
b) An example of one of the tokens Braintree is returning to you?

**Comment by thefotios** [comment] 2020-04-03 02:03
@bluepnume This is our React component - [Here's a gist](https://gist.github.com/thefotios/6baba4d7cd9ce3d6f0f5590716f3fe77) and we're running `braintree-web@3.57.0`

The attached log has the braintree token as well as a stack track if that's helpful
[localhost-1585878898297.log](https://github.com/paypal/paypal-checkout-components/files/4424660/localhost-1585878898297.log)

**Comment by bluepnume** [comment] 2020-04-03 02:24
Hi @thefotios -- thank you so much, this was enough to narrow it down. It looks like the api is incorrectly returning this as a `capture` and not an `authorize` which is why the validation is failing during validation step in the sdk/button.

For now I'm disabling this validation for this specific case. I apologize for the inconvenience here; I'll raise an internal ticket for that API layer to help track down the root cause of the issue.

Thanks again for helping narrow this one down.

**Comment by bluepnume** [comment] 2020-04-03 02:26
@crookedneighbor -- just tagging you here since I'm not sure where this issue originates. 

Can you confirm, when the following is passed to Braintree:

```
   instance.createPayment({
      enableShippingAddress: true,
      intent: 'authorize',
      flow: 'vault',
    })
```

What is the `intent` that is subsequently passed to the PayPal API? Is it `authorize`?

**Comment by thefotios** [comment] 2020-04-03 02:35
@bluepnume Thanks for taking care of this! Do you know when these changes will do live or is ther anything I can test out?

As for the intent being passed, this is what tipped us off that something changed - https://github.com/braintree/braintree-web/blob/master/src/paypal-checkout/paypal-checkout.js#L847-L850. You can trace that back to the `createPayment` call in the same class

**Comment by bluepnume** [comment] 2020-04-03 02:37
On second look, seems like `intent` is not being passed to https://api.sandbox.braintreegateway.com/merchants/hh4cpc39zq4rgjcg/client_api/v1/paypal_hermes/setup_billing_agreement --

<img width="711" alt="Screen Shot 2020-04-02 at 7 35 23 PM" src="https://user-images.githubusercontent.com/1219075/78318291-390ce500-7519-11ea-9383-0dfe2fa1ac5f.png">

So I assume `capture` (or `sale`) must be being set as the default on the BT server side since nothing is being passed...

**Comment by bluepnume** [comment] 2020-04-03 02:42
@thefotios temporary fix is pushed. Please let me know if you still see the issue.

**Comment by thefotios** [comment] 2020-04-03 03:18
@bluepnume Just tested against sandbox and it's working for me.

As for `braintree-web`, we're running a Rails app with distinct front and back ends. In our case, everything about the form submission is client side (except that we get a client ID from our backend). We authorize the transaction afterwards on the backend, but it's not even getting that far. Out of curiosity, which object did you dump there?

**Comment by bluepnume** [comment] 2020-04-03 17:56
@thefotios -- looks like the `intent: 'authorize'` you're passing to Braintree is having no effect. I recommend:

- Remove that intent from your call
- Set `intent=capture` when invoking the paypal sdk.

That should guarantee future stability here.

**Comment by crookedneighbor** [comment] 2020-04-03 19:03
When using the billing agreement flow, intent should not be passed at all. In the BT SDK, it will just be ignored. In the PayPal SDK, you must omit the `intent` query parameter.

**Comment by thefotios** [comment] 2020-04-03 19:37
@crookedneighbor Ok, it's also entirely possible we're doing the wrong thing here (maybe we should be using something other than `createBillingAgreement`). We're not using braintree or PayPal recurring/subscription capabilities. We're using the authorized token in our own OOB renewal process.

**Comment by bluepnume** [comment] 2020-04-03 21:28
Definitely recommend working with the Braintree team to figure out the correct integration here. That said -- in the mean time, I still highly recommending switching over to `intent=capture` in the sdk url and removing `intent` from the Braintree call.

**Comment by cusero** [comment] 2020-04-07 11:46
> Hi @thefotios -- can you let me know exactly what you're seeing? Capture was always the default, per https://developer.paypal.com/docs/checkout/reference/customize-sdk/#intent
> 
> What are you passing in the script tag, and what are you passing when setting up the transaction?

Not sure the above helps my case. Still seeing the error when the PayPal window is closed quickly before it loads - just to start with :(

To give a bit more background history...

We are passing no intent at all! We use PayPal with a vault flow as such:
`https://www.paypal.com/sdk/js?client-id=${clientID}&locale=${locale}&disable-funding=card,credit&vault=true`

Using `braintree-web` @ `v3.60.0` and create the payment like:
`paypalCheckoutInstance.createPayment({ flow: 'vault', enableShippingAddress: false })`

Since we have a subscription model, after the payment is accepted (i.e. calling https://api.sandbox.braintreegateway.com/merchants/4ffdb9nd2z9gsm3d/client_api/v1/paypal_hermes/setup_billing_agreement). We get a response like below to be tokenized and get a nonce in return (similar to what @thefotios mentioned above):
<img width="745" alt="Screen Shot 2020-04-07 at 12 43 40" src="https://user-images.githubusercontent.com/14952750/78665333-8e584600-78cd-11ea-89f1-d2a1add562ab.png">

But the final steps of the payment all work as expected :) It's only the PayPal SDK 'errors' that are a slight nuisance in the console. If they could be caught somehow from the `onError` callback passed to `paypal.Buttons({})`!

**Comment by bluepnume** [comment] 2020-04-22 20:30
Hi @cusero -- sorry, the discussion got a little sidetracked on an unrelated issue. I'll take a look at the problem you initially reported. Thanks.

**Comment by komakino** [comment] 2020-05-22 10:02
Any news on this? We're experiencing the same issue.

**Comment by DeveloperHW** [comment] 2020-05-27 14:07
same issue here ! as soon as I click the PayPal button - window opens & closes with 422 generic error

**Comment by bluepnume** [comment] 2020-05-28 21:38
This should now be resolved. Please let me know if you still see the issue. Thanks!

**Closed by bluepnume** 2020-05-28 21:38 UTC

**Comment by cusero** [comment] 2020-05-29 08:17
Issue resolved, indeed! Thank youuu @bluepnume 🙌

**Comment by mateja176** [comment] 2020-07-23 13:19
Still experiencing the issue, right after the `div` containing the buttons is unmounted.

**Comment by csheppard** [comment] 2020-07-23 13:42
Yes I was still getting the window closed error in my Vue SPA.

It's not ideal but I got around it by executing the PayPal SDK every time I want to render the button, e.g. append the javascript SDK to the document head and call window.paypal within the script.onload.

**Comment by Soulpancake000** [comment] 2020-08-19 10:49
Yes, the Issue is still there.
![image](https://user-images.githubusercontent.com/36916707/90625774-b66e9300-e237-11ea-9dd4-52b4b1645707.png)

**Comment by zarpio** [comment] 2021-03-22 13:32
Facing same issue :-(
A boolean is being passed as a fourth parameter to window.open. This is not used and may cause an exception in a future release.
