### ISSUE TITLE
[Bug] Unexpected behavior when closing the PayPal window before it loads

### ISSUE THREAD

**Issue by romrz** [paypal/paypal-checkout-components#1339] opened 2020-06-17 19:01 UTC
### 🐞 Describe the Bug
There is an issue when the PayPal popup window is closed before it loads. It shows a loading element that keeps loading forever and the PayPal button is no longer clickable.

It seems it only happens when there's an `onClick` callback. For some reason it makes the window load slower, it seems.

### 🔬 Minimal Reproduction
* Add an `onClick` callback to the Buttons implementation.
* Click the PayPal button
* Close the popup window before it loads

Here's a codepen where you can reproduce it: https://codepen.io/romrz/pen/GRoNQKx

### 😕 Actual Behavior
The window is closed, but then the overlay appears with a loading element that keeps loading forever. No console errors are shown.
After closing that overlay, the PayPal button is left unresponsive.

### 🤔 Expected Behavior
The popup window is closed and then you can click the PayPal button again to re-initiate the payment process

### 🌍 Environment

- Browser version: 81.0.4044.129
- OS version: Mac OS Catalina (10.15.4)
- SDK version (`window.paypal.version`): 5.0.128

### Affected browsers
Tested on Chrome and FireFox

### ➕ Additional Context
Here's a video of the issue in the codepen shared above: https://share.vidyard.com/watch/1jAbWvn7Z925VpDePdH4mx?

**Comment by mnicpt** [comment] 2020-06-17 20:03
Hi, @romrz!  I was unable to reproduce following the steps above.  Can you open a new incognito window and try again?

**Comment by mnicpt** [comment] 2020-06-17 20:10
@romrz Do you have a live site that this was occurring in?

**Comment by romrz** [comment] 2020-06-17 20:29
Thanks for the reply @mnicpt. Yes, it's happening on a live site (I'll share it with you if you can't reproduce). But I think you just have to be quick enough to close the window before the background overlay shows up. You can also try using a keyboard shortcut to close the window faster (cmd + w on mac, ctrl + w on ubuntu and ctrl + shift + w on windows I think).

**Comment by romrz** [comment] 2020-06-17 20:31
@mnicpt and it's not happening on your live site because it seems it only happens when you have an `onClick` callback on the buttons implementation.

**Comment by mnicpt** [comment] 2020-06-17 20:34
@romrz You can add `onClick` on our site and it will refresh.  I was able to reproduce on CodePen for the Credit button only, but maybe I wasn't clicking fast enough.

**Comment by romrz** [comment] 2020-06-17 20:45
@mnicpt I added `onClick` on your live site and I was able to reproduce it there too: https://share.vidyard.com/watch/cfwQbhRLAzvsDekk5A6cZz?

**Comment by mnicpt** [comment] 2020-06-17 20:47
@romrz Thanks for confirming.

**Comment by mnicpt** [comment] 2020-06-18 17:33
@romrz I was able to reproduce.  While this is an edge-case, I am looking into a fix.  Thank you for your patience.

**Comment by romrz** [comment] 2020-06-18 18:22
@mnicpt Thank you very much!

**Comment by mnicpt** [comment] 2020-07-09 13:13
@romrz This has been fixed in the latest release.  Thank you for bringing this to our attention.

**Closed by mnicpt** 2020-07-09 13:13 UTC
Labels: bug

**Comment by romrz** [comment] 2020-07-09 15:29
Thank you very much for taking care of this @mnicpt

**Comment by mnicpt** [comment] 2020-07-09 18:48
My pleasure @romrz :)
