### ISSUE TITLE
Can't open login in paypal modal on IOS/Android webview (seems like missing CSP issue)

### ISSUE THREAD

**Issue by zvihersh** [paypal/paypal-checkout-components#1316] opened 2020-05-21 18:14 UTC
### Description

Please provide a short description of the issue here, along with:
after press on the paypal-checkout button the login screen just spin forever

- Screenshots or videos that show the issue
checkout:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25309866/82591313-d5617880-9ba7-11ea-9284-08d40fdbe3b1.gif)

the log in the console:
![chrome_2020-05-21_20-51-45](https://user-images.githubusercontent.com/25309866/82590415-56b80b80-9ba6-11ea-9205-b43e9136d153.png)

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment] 2020-05-21 18:17
Are those the only errors you see in the console? Any errors in network tab?

**Comment by bluepnume** [comment] 2020-05-21 18:19
@jainmitesh09 can you take a look please? Seems to be failing on UL page. I can repro in chrome with a simulated webview user agent, when testing at https://developer.paypal.com/demo/checkout/#/pattern/client

**Comment by zvihersh** [comment] 2020-05-21 18:21
> Are those the only errors you see in the console? Any errors in network tab?

@bluepnume yes those are the only errors in the console.
p.s. in the network tab those errors are also present but not other errors

**Comment by bluepnume** [comment] 2020-05-21 18:23
I see:

```
Error: Blocked a frame with origin "https://www.sandbox.paypal.com" from accessing a cross-origin frame.
    at https://c.paypal.com/webstatic/r/fb/fb-all-prod.pp2.min.js:1:57324
    at https://c.paypal.com/webstatic/r/fb/fb-all-prod.pp2.min.js:1:59357
```

Not sure if this is the root cause or not.

**Comment by jainmitesh09** [comment] 2020-05-21 19:03
@bluepnume Is that to do with FN script? PS I can only repro in SB.

**Comment by bluepnume** [comment] 2020-05-21 22:08
We found the issue. Working on getting a fix out

**Comment by jainmitesh09** [comment] 2020-05-27 02:00
@zvihersh This issue seem to be fixed as @bluepnume mentioned. Please try again and close the issue if no longer able to repro. Thank you!

**Closed** 2020-05-27 05:48 UTC
