### ISSUE TITLE
[Bug] Error for vault in paypal ( enabling it for subscription )

### ISSUE THREAD

**Issue by joyyycheng** [paypal/paypal-checkout-components#1518] opened 2021-01-13 01:48 UTC
Hello im trying to do a subscription for my app using paypal. I created the subscription plan and product in sandbox as it is still a test account. When I implement the codes into my ionic app, I get this error.
![image](https://user-images.githubusercontent.com/68642009/104395696-3fd68700-5584-11eb-8498-b06214b12294.png)
This is the script code that I added to the index.html

```
<script
  src="https://www.paypal.com/sdk/js?client-id=qwe...&vault=true">
</script>
```
I have also added the code in my .ts page here
```
setTimeout(() => {
  // Render the PayPal button into #paypal-button-container
  <any>window['paypal'].Buttons({

    // Set up the transaction
    createOrder: function (data, actions) {
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: _this.data.paymentAmount
          }
        }]
      });
    },

    // Finalize the transaction
    onApprove: function (data, actions) {
      return actions.order.capture()
        .then(function (details) {
          // Show a success message to the buyer
          alert('Transaction completed by ' + details.payer.name.given_name + '!');
          console.log(details)
        })
        .catch(err => {
          console.log(err);
        })
    }
  }).render('#paypal-button-container');
}, 500)
```
Inside the sandbox of my paypal account, I have enabled vault as well.
![image](https://user-images.githubusercontent.com/68642009/104395764-672d5400-5584-11eb-8734-137e5496b613.png)
I am not really sure what else I can do to enable the vault to be true.

**Comment by mstuart** [comment] 2021-02-01 16:26
Dupe of https://github.com/paypal/paypal-checkout-components/issues/1519

**Closed by mstuart** 2021-02-01 16:26 UTC
