### ISSUE TITLE
[Bug] onApprove never executes when 'Click to Continue' link is used to refocus popup

### ISSUE THREAD

**Issue by halloweenman** [paypal/paypal-checkout-components#1813] opened 2021-12-13 10:49 UTC
### 🐞 Describe the Bug
onApprove never executes and the user is left hanging when the following steps are taken:

1. User is presented with PayPal buttons.
2. User clicks on PayPal button.
3. User is presented with PayPal payment window/pop up (**_make sure no PayPal user is already logged in_**) and clicks outside the window/pop up so it disappears.
4. User clicks on 'Click to Continue' to re-launch PayPal window and completes payment as normal.

If the above steps are taken then payment will succeed but onApprove will never be executed leaving the user hanging. It's when the user clicks outside the PayPal window/pop up that causes the issue.

### 🔬 Minimal Reproduction
As described above. See https://cvcouktest.web.app and use username sb-cb0on8784435@personal.example.com  and password 'paypaltest'.

The repo is simply using PayPal's own Sample JavaScript SDK code:

```
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Ensures optimal rendering on mobile devices -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" /> <!-- Optimal Internet Explorer compatibility -->
  </head>

  <body>
    <!-- Include the PayPal JavaScript SDK; replace "test" with your own sandbox Business account app client ID -->
    <script src="https://www.paypal.com/sdk/js?client-id=AQhEttS_F3vYx3lXwoHFx6kABJSo5K1iM17OH16dhOQmEiaIQqzTqnMTiPl66cRdbbBKOiNCc6-y63VA&currency=USD"></script>

    <!-- Set up a container element for the button -->
    <div id="paypal-button-container"></div>

    <script>
      paypal.Buttons({

        // Sets up the transaction when a payment button is clicked
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: '77.44' // Can reference variables or functions. Example: `value: document.getElementById('...').value`
              }
            }]
          });
        },

        // Finalize the transaction after payer approval
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(orderData) {
            // Successful capture! For dev/demo purposes:
                console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                var transaction = orderData.purchase_units[0].payments.captures[0];
                alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

            // When ready to go live, remove the alert and show a success message within this page. For example:
            // var element = document.getElementById('paypal-button-container');
            // element.innerHTML = '';
            // element.innerHTML = '<h3>Thank you for your payment!</h3>';
            // Or go to another URL:  actions.redirect('thank_you.html');
          });
        }
      }).render('#paypal-button-container');

    </script>
  </body>
</html>
```

### 😕 Actual Behavior
onApprove fails to execute.

### 🤔 Expected Behavior
You would expect onApprove to execute.

### 🌍 Environment

- Browser version: Safari Version 15.1 (15612.2.9.1.30, 15612)
- OS version: -  macOS 10.15.7
- SDK version (`window.paypal.version`): - latest

### Affected browsers
What browser(s) are affected?

Only tested on

- Chrome
- Safari

**Comment by VasApps** [comment] 2022-01-01 19:12
Any update on this? This is a critical bug for us and it's happening in production. Can we get this resolved asap?

**Comment by halloweenman** [comment] 2022-01-02 09:35
I'm not sure anyone at PayPal is even looking at this repo issue as it's been 20 days now without a response which is pretty shocking.

I logged a fault www.paypal-support.com where are more likely to receive a response.

**Comment by VasApps** [comment] 2022-01-02 22:17
> I'm not sure anyone at PayPal is even looking at this repo issue as it's been 20 days now without a response which is pretty shocking.
> 
> I logged a fault [www.paypal-support.com](http://www.paypal-support.com) where are more likely to receive a response.

Yeah I logged a fault as well and got a generic response back telling me that they see no issues but there is clearly an issue that happens EVERY time in production mode. This is a severe issue for guest checkouts. Hope someone sees this repo and fixes this asap. For now I had to manually hide that black overlay using JavaScript as a workaround.

**Comment by wsbrunson** [comment] 2022-01-05 15:14
Hi @halloweenman & @VasApps 

First off, thank you for the report and being patient with us. The JS SDK team can also reliably reproduce this on our end. We are currently investigating a fix for this issue. We will keep you up to date here in this thread as the fix might ultimately be in one of our other repos.

**Comment by rmuchall** [comment] 2022-01-26 09:48
@wsbrunson
Is there any update on this issue?

**Comment by stefanosalvucci** [comment] 2022-01-28 18:04
@wsbrunson 
is there any update? 23 days is a quite long amount of time 
We have this issue happening consistently on our production environment and our customers are not happy.

**Comment by wsbrunson** [comment] 2022-01-31 15:58
Hey y'all, sorry for the radio silence! Here's where the actual fix is happening: https://github.com/krakenjs/post-robot/pull/96

Looks like its been approved, just not merged. We'll get this into our Wednesday release of the SDK as long as there are no additional problems.

**Comment by wsbrunson** [comment] 2022-02-02 22:04
New ETA: tomorrow morning, 3 Feb 2022 sometime before 12pm Central

**Comment by RoudyTarabay** [comment] 2022-02-03 05:24
@wsbrunson Thanks a lot, please keep us posted.

**Comment by wsbrunson** [comment] 2022-02-03 18:43
Version `5.0.280` of the SDK is now in production which includes the fix to this issue (open console and type `window.paypal.version`). You should see it either immediately or in the next few hours as edge and browser cache expire. I'll leave this issue open for at least the next day to let y'all verify as well.

**Closed** 2022-02-07 15:49 UTC
