### ISSUE TITLE
Web PayPal unable to display login window on Android mobile phone

### ISSUE THREAD

**Issue by isuex** [paypal/paypal-checkout-components#1072] opened 2019-04-03 03:18 UTC
### Description

- Originally, I wanted to use WebView to embed Web PayPal in Android application. I encountered some problems in using it. After clicking the payment button, I always showed loading. Normally, I should jump into PayPal account input to complete payment after loading.
![](http://isuex.com/loading.jpg)

- I am connected to the latest checkout.js to the PayPal JavaScript SDK. https://developer.paypal.com/docs/checkout/integrate/#2-add-the-paypal-script-to-your-web-page
The following figure (the simplest test code):
![](http://isuex.com/html.png)

- After encountering the above problems, I tried to open this page directly through the browser (UC, QQ and other browsers), but it can be used normally on the iPhone. Strangely enough, if I try to change the UA mode of the browser to the lack of an iPhone, it will work.
After setting up UA browser for the same mobile phone:
![](http://isuex.com/UA.jpg)
![](http://isuex.com/UAx.jpg)
Unsupported：Mozilla/5.0 (Linux; U; Android 8.0.0; zh-cn; MIX 2 Build/OPR1.170623.027) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 MQQBrowser/9.1 Mobile Safari/537.36
Support：Mozilla/5.0 (iPhone; U; CPU iPhone OS 5_0 like Mac OS X; en-us) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3

- I also considered modifying http-equiv = "X-UA-Compatible" content = "" directly through HTML, but the result page failed.
- After consulting the official documents, I learned that Mobile Browser's support made me try to install chrome, Firefox and Samsung. Is it true that our Web PayPal only supports these? If this is a strange question, why does the official PayPal Demo (https://demo.paypal.com/us/demo/home) not support the browser (UC, QQ browser) above me? Is it good in the middle?

### Affected browsers

- [x] QQ
- [x] UC
- [x] Web View (Android)

test url http://isuex.com/paypal.html

Have you ever met before? If you really can't get a solution, it's OK to send out a solution with suggestions. Thank you very much.

@dshaw @bluepnume

**Comment by Erlix322** [comment] 2019-04-07 15:56
+1 I can confirm this error/bug... any updates on this?

**Comment by bluepnume** [comment] 2019-04-08 18:02
Closing as a duplicate of https://github.com/paypal/paypal-checkout-components/issues/1061 -- found the cause of this and tracking internally.

**Closed by bluepnume** 2019-04-08 18:02 UTC

**Comment by wanlerong** [comment] 2019-04-18 06:17
same here. In sandbox envirment, when i use a US country business account

@bluepnume
