### ISSUE TITLE
[Bug] Express checkout payment not working in iPhones

### ISSUE THREAD

**Issue by abdoulosseni** [paypal/paypal-checkout-components#2180] opened 2023-06-08 14:23 UTC
### 🐞 Describe the Bug

I am using Express checkout js SDK client-side REST integration in my application and Express checkout functionality is not working properly in iPhones. I used  https://developer.paypal.com/demo/checkout/ to make tests

--
The issues are:
- Payment popup is not responsive in iPhones, the popup is not completely visible to the user.
- Payment popup scroll is not properly working

---
How to reproduce this issue?

Video demonstration : https://youtube.com/shorts/KA5wsnCND4k

env: sandbox
PayPal payment: https://developer.paypal.com/demo/checkout
Useragent : Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

Device: Iphone 13 mini
Using: Web View / Safari ViewController

**Comment by henry-95** [comment] 2023-07-07 14:35
Having this issue as well. Paypal button does not load on Safari browser. I've had a look at the Safari web inspector and checked the Network tab, the Paypal SDK is just stuck on loading and never actually gets loaded for some reason. There is some demo code here you can easily recreate the issue using Safari on iOS:
https://threedsecure.onrender.com/

**Comment by devchristina** [comment] 2023-09-13 19:09
Hi All -- apologies in the delayed acknowledgement and response. Can someone confirm that this issue is still occurring?

**Comment by abdoulosseni** [comment] 2023-09-14 07:40
I confirm that we are still experiencing this issue.

**Comment by pixiejohn** [comment] 2023-09-20 14:58
I have the same problem on multiple clients sites. Is this being looked at?
I have problems specifically with Safari 16.6.

**Comment by sebastianfdz** [comment] 2023-11-29 17:13
Hello all! Sorry for the delayed response. I'd like to gather some additional details to better understand the situation:

1. Regarding the video demonstration, could you confirm whether it was recorded using an actual iPhone or an emulator? We attempted to replicate the scenario on an iPhone, but unfortunately, we couldn't reproduce the bug.

2. Does this bug specifically arise when using a web view? We're actively working on narrowing down this issue. It's worth noting that web views can sometimes introduce CSS inconsistencies, as they wrap around the Safari browser. While we are addressing this, we officially recommend against using web views for PayPal web pages. For more details, please check out our [security guidelines](https://developer.paypal.com/api/rest/reference/info-security-guidelines/#link-donotuseawebviewtodisplaypaypalwebpageswithinyourapplication).

3. Has this issue been observed on Safari without the use of a web view? The expected behavior in this scenario should be the opening of a new tab with the popup.

Best regards.

**Comment by sebastianfdz** [comment] 2023-11-29 17:16
> Having this issue as well. Paypal button does not load on Safari browser. I've had a look at the Safari web inspector and checked the Network tab, the Paypal SDK is just stuck on loading and never actually gets loaded for some reason. There is some demo code here you can easily recreate the issue using Safari on iOS: https://threedsecure.onrender.com/

Hello @henry-95 ! This seems like a separate problem from the popup issue on IOS Safari. To ensure that we give your matter the attention it deserves and can track and manage it effectively, could you please open a new issue specifically for this problem? This will allow us to investigate and resolve the issue more efficiently while keeping our communication organized.

Best regards.

**Comment by devchristina** [comment] 2024-01-02 14:58
Closing this issue. As advised, please create a new issue if additional support is required.

**Closed by devchristina** 2024-01-02 14:58 UTC
Labels: 🐞 bug, 🥀 needs-reproduction
