### ISSUE TITLE
Error: Window closed when SDK used with lit-element

### ISSUE THREAD

**Issue by lpellegr** [paypal/paypal-checkout-components#1107] opened 2019-05-14 14:55 UTC
### Description

I am integrating Paypal checkout button in a [lit-element](https://github.com/Polymer/lit-element) application. Basically, it makes use of web components: the Paypal button is rendered in a web component.

When integrated, the button appears for **about 3 seconds** and then disappears with the following error in the console:

> js?client-id=sb:1 unhandled_error {err: "Error: Window closed↵    at https://www.paypal.com…ttps://www.paypal.com/sdk/js?client-id=sb:1:5619)", timestamp: "1557844962340", referer: "lit-element-paypal-checkout.stackblitz.io", uid: "8e52c2e48d_mtq6nde6ndm", env: "sandbox"}
> ...

The error occurs consistently in _sandbox_ and _production_ environments.

Paypal SDK version is `5.0.29`.

The issue is the same on Chrome 74 and Firefox 66. I did not test with other browsers but I suspect it is too and related to an incompatibility with web components.

Any ideas or guidance to fix this problem is welcome.

### Steps to reproduce

Here is the link to a live reproduction:

https://lit-element-paypal-checkout.stackblitz.io/

and the associated code:

https://stackblitz.com/edit/lit-element-paypal-checkout?file=index.js

### Affected browsers

- [x] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by NeilujD** [comment] 2019-05-15 18:32
I have exactly the same issue using Polymer (also web components).
Just to compare @lpellegr can you provide the code that integrate your paypal button ?

For my part here it is :
```js
paypal.Buttons({
  createOrder: function(data, actions) {
    // Set up the transaction
    let order = actions.order.create({
      purchase_units: [{
        amount: {
          reference_id: "XXX",
          value: "0.01"
        },
        custom: "123"
      }]
    });
    return order;
  },
  onApprove: function(data, actions) {
    // Capture the funds from the transaction
    return actions.order.capture().then(function(details) {
      console.log("success", details);
    });
  },
  onError: function(error) {
    console.log(error);                      
  },
  onCancel: (data, actions) => {
    console.log(data, actions);
  },
}).render(this.shadowRoot.querySelector("#paypalButton"));
```

**Comment by lpellegr** [comment] 2019-05-15 18:44
@NeilujD You can find a link to the code used in the section _Steps to reproduce_ above. It uses the minimal code shown in the official Paypal example: `window['paypal'].Buttons().render(...)`.

Would love to make some progress on this issue, at least to find a workaround. Until now that's a blocking issue that prevents us to use Paypal.

**Comment by NeilujD** [comment] 2019-05-16 09:28
It seems to be caused by the `watchForClose` method but I do not know why yet.

**Comment by lpellegr** [comment] 2019-05-17 08:38
@bluepnume Any ideas about what's the problem?

**Comment by NeilujD** [comment] 2019-05-27 09:03
@lpellegr did you find any workaround about it ?

**Comment by lpellegr** [comment] 2019-05-27 09:49
@NeilujD I ended up using the Paypal REST API instead. It requires more work to have a full working flow but it works with no SDK on client side.

**Comment by NeilujD** [comment] 2019-05-27 11:44
@lpellegr I agree.
Thank you for your feedback.
Do you think you could provide a LitElement component or a code sample that could help me moving forward ?

**Comment by NeilujD** [comment] 2019-05-28 16:14
@lpellegr I just figured out a workaround using the client SDK.
It is not as clean as I would like but it works great and it is compliant with Shadow-DOM.

Basically I just create the `div#paypalButton` tag at the root of my app (in index.html) but I insert it in my mais app element as a slot.
Then I pass the slot to the children until it is present in my checkout element.
Next I just need to call the Paypal Buttons initialize function using as a container selector `document.getElementById("#paypalButton")`.

I also identify the source of the problem :
To check if the Paypal frame is still opened the script looking up for the frame element using `document.contains(frame)` which is not Shadow-DOM compliant if the container is not at the document root.

**Comment by bluepnume** [comment] 2019-07-02 20:50
Closing this since right now we have no known fix or plans to support shadow-dom. We'll revisit this in future if there's sufficient demand.

**Closed by bluepnume** 2019-07-02 20:50 UTC

**Comment by lpellegr** [comment] 2019-07-02 20:53
That's really sad. Web components and shadow-dom are supported by all major
browsers. Paypal lives in the past...

Le mar. 2 juil. 2019 à 22:51, Daniel Brain <notifications@github.com> a
écrit :

**Comment by anatoliyarkhipov** [comment] 2019-07-03 07:06
Also, absolutely the same problem happens if I use PayPal Checkout in a WebView with [Turbolinks Android](https://github.com/turbolinks/turbolinks-android). I wasn't able to fully debug it, and as a workaround I just disabled Turbolinks on the page where the PayPal button is rendered. Also, it works fine with Turbolinks if I open the page through a browser on my desktop. The problem appears only on mobile devices.

**Comment by bzitzow** [comment] 2019-09-17 23:29
+1 - looking for a fix 👍

**Comment by midesweb** [comment] 2019-10-03 16:31
Same issue when using web components shadow-dom. I have resolved this situation by implementing the render button element in the root document and using slots, as described by @NeilujD

**Comment by ToledoNicola** [comment] 2019-10-18 13:35
hi, i have the same problem in ionc 4, someone found a workaround?

**Comment by lucascco** [comment] 2019-11-14 14:19
Hi, I faced the same issue using StencilJs, some solution new?

**Comment by daneesv** [comment] 2019-11-19 00:20
If you're use jQuery, "$(document).ready" resolve the problem.
**$(document).ready(function(){**
        paypal.Buttons({ }).render("#payment-subscription-paypal");
**});**

**Comment by mar-ku** [comment] 2019-11-28 18:27
> @lpellegr I just figured out a workaround using the client SDK.
> It is not as clean as I would like but it works great and it is compliant with Shadow-DOM.
> 
> Basically I just create the `div#paypalButton` tag at the root of my app (in index.html) but I insert it in my main app element as a `slot`.
> Then I pass the `slot` to the children until it is present in my checkout element.
> Next I just need to call the Paypal Buttons initialize function using as a container selector `document.getElementById("#paypalButton")`.
> 
> I also identify the source of the problem :
> To check if the Paypal frame is still opened the script looking up for the frame element using `document.contains(frame)` which is not Shadow-DOM compliant if the container is not at the document root.

This solution also worked for me on a Vue js application; passing the container div via slots from a a parent component.

**Comment by Misiu** [comment] 2019-12-04 13:38
@bluepnume the same error occurs on your website.

Steps to reproduce:

1.  Go to https://developer.paypal.com/demo/checkout/#/pattern/client
2.  Click on PayPal button
3. Close the popup windows
4. The error occurs

![image](https://user-images.githubusercontent.com/1741838/70146991-b1ff4b80-16a3-11ea-9e98-2360d9e45808.png)

**Comment by brayanL** [comment] 2020-01-17 14:31
What is the solution PayPal Team?

**Comment by Misiu** [comment] 2020-01-17 14:51
@brayanL I contacted PayPal and the only solution they suggested it so use REST API and not use this component.
I also got info that my description (almost identical to my comment) will be pass to the development team, but I didn't get any reply from them, still waiting for info. I'll let you updated if I get anything.

**Comment by uchathura** [comment] 2020-03-05 08:39
I also have the same error. Can anyone give me the solution?

**Comment by Misiu** [comment] 2020-03-05 08:53
@uchathura I've contacted PayPal, I got info that this will be fixed in the next version, but it looks like those were only promises.
Still waiting for the fix.
Try contacting them, maybe you will have more luck.

**Comment by midesweb** [comment] 2020-03-05 09:03
> I also have the same error. Can anyone give me the solution?

Put the paypal buttons on the main page document, and use slots to render the buttons inside your web components.

**Comment by Jriles** [comment] 2020-04-05 04:03
Bad

**Comment by dan003400** [comment] 2020-05-07 19:41
> @NeilujD I ended up using the Paypal REST API instead. It requires more work to have a full working flow but it works with no SDK on the client side.
> 
> Overall, I am quite disappointed by the Paypal experience as a developer: no official feedback on created issues, documentation not really clear, REST v1 API deprecated but stable clients only available for v1, webhooks not working with sandbox and 4 days to acknowledge the issue, etc.

PayPal is the worst developer experience on the web, probably even worse if you are a merchant as well.

**Comment by dan003400** [comment] 2020-05-07 19:43
So from the looks of it, this issue is being treated the same way all issues are treated with PayPal.

No response, no fix, a continued terrible developer experience.

Got it.

**Comment by Misiu** [comment] 2020-05-07 19:55
@bluepnume any comments on this? Maybe you guys could reconsider supporting this.
As you can see there is a demand to use PayPal in shadow-dom scenarios.
Frameworks like React are getting more and more popular. I see more and more sites built using web components.
Why not help them? In the end, if more people will use your SDK you will earn more money. There is no stronger argument.

**Comment by dan003400** [comment] 2020-05-07 20:00
PayPal doesn't even know what React is, they still are using technologies from the jQuery Mobile era 😂 

Take a look at their stack or dashboards, 10 second load times with random app / layout switches as you navigate through the dashboards.

Not to mention 100 Deprecation warnings and errors through all their developer docs.

**Comment by bluepnume** [comment] 2020-05-08 00:25
Hi @Misiu -- we did actually add support for shadow-dom to https://github.com/krakenjs/zoid which powers the paypal sdk. Can you let me know if you're seeing a specific issue rendering into the shadow dom? If it doesn't work, please open a new issue and we'll help debug.

There is also a React demo at https://github.com/paypal/paypal-checkout-components/blob/master/demo/react.htm -- this has been working for many years.

@dan003400 appreciate it if you can keep it constructive. We're all trying to do our jobs, and provide the best possible developer experience. If you have specific constructive feedback we'd be very glad to hear it and act on it.

**Comment by dan003400** [comment] 2020-05-08 18:42
I am being constructive, sometime the truth hurts and thats what it takes to make things happen.

There is clearly issues on the PayPal tech stack, it always feels very old and slow.

Take a look at how slow your PayPal Checkout modal pops and loads, it legit loads for 4-6 seconds on a good day, whats up with this? Its simply loading a login form....

It would be nice to have a simple singular API like any of the new companies in the payment tech like Stripe, take a look at their docs, a singular place to see all their docs, a clear understanding how the whole system works.

When I try to do the same on the PayPal site, I am mislead to multiple features that are still in production but no longer useable? There should be a single source of truth and a single way to implement a simple PayPal checkout.

ie. PayPal Express, create payment method tokens, use a REST API to charge this token again in the future, then you guys destroyed that with a less featured harder to customize experience with PayPal "Smart" Buttons.

PS - Why is this issue closed? The issue is still happening....

**Comment by bluepnume** [comment] 2020-05-09 01:57
> PS - Why is this issue closed? The issue is still happening....

The test page from the original issue now works. If you're still seeing an issue, please raise a new ticket and share the details.

**Comment by zeinabYounes** [comment] 2020-08-19 18:56
try to remove any javascript  file

**Comment by beitomartinez** [comment] 2020-12-07 14:33
The slot solution works for VueJS as @mar-ku mentioned.
Or, you can create a new component (which will contain the buttons) and call the render function on mounted.

**Comment by stucker71** [comment] 2021-04-28 08:31
> @lpellegr I just figured out a workaround using the client SDK.
> It is not as clean as I would like but it works great and it is compliant with Shadow-DOM.
> 
> Basically I just create the `div#paypalButton` tag at the root of my app (in index.html) but I insert it in my main app element as a `slot`.
> Then I pass the `slot` to the children until it is present in my checkout element.
> Next I just need to call the Paypal Buttons initialize function using as a container selector `document.getElementById("#paypalButton")`.
> 
> I also identify the source of the problem :
> To check if the Paypal frame is still opened the script looking up for the frame element using `document.contains(frame)` which is not Shadow-DOM compliant if the container is not at the document root.

Thanks for the workaround suggestion. I have a similar problem in Polymer. Would you be able to provide actual code example of the div#paypalButton in your html file and the slot code in your main app element? Thanks.
