### ISSUE TITLE
IE11 pop up appears then closes itself

### ISSUE THREAD

**Issue by alisonp** [paypal/paypal-checkout-components#1092] opened 2019-05-03 11:53 UTC
Using the Payments SDK orders v2
Clicking on the “PayPal” button, the popup appears and the just closes.

Steps to reproduce

https://staging.rnib.panlogic.co.uk/donations-and-fundraising/donate-now
Click on PayPal button

https://developer.paypal.com/demo/checkout/#/pattern/client 
Pop up will appear but it is blank.

 Affected browsers

- [ ] IE 11

**Comment by bluepnume** [comment] 2019-05-03 23:42
I'm not able to reproduce this one. Can you confirm if https://developer.paypal.com/docs/checkout/troubleshoot/internet-explorer/ helps?

**Comment by alisonp** [comment] 2019-05-14 10:59
The merchant is aware of this and tried this but it did not resolve the issue.
Thanks

**Comment by alisonp** [comment] 2019-05-15 11:00
The merchant has retested this issue and now what appears to be happening is that the PayPal window remains open but does not actually load. The loading spinner continues while no page is loaded into the window.
I tested this also in this browser and experienced the same.
Thanks

**Comment by bluepnume** [comment] 2020-04-22 20:00
Hi -- closing this one as we've been unable to reproduce and a lot of time has passed without similar reports. Recommend trying with the latest sdk, and opening a new issue if you're still seeing the same problem. Thank you!

**Closed by bluepnume** 2020-04-22 20:00 UTC
